# Podfile content
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'IOSDemo' do
    # React Native
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"
    pod 'React', path: "#{rn_path}", :subspecs => [    
      'Core',
      'CxxBridge',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport',
      
    ]
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    
    # Required by Google Map, ignore if you use Apple Map
    pod 'GoogleMaps' 
    pod 'Google-Maps-iOS-Utils' 
    pod 'GoogleUtilities'
    pod 'GoogleAppMeasurement' 

    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path # <~~ if you need GoogleMaps support on iOS
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'Firebase/Core' 
    pod 'Firebase/Messaging' 

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
    pod 'GoogleSignIn'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "react-native-google-maps"
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
          target.remove_from_project
        end
    end
end